version: '3'
services:
  app1:
    build:
      context: ./app1
    container_name: app1
    ports:
      - "8081:80"  

  app2:
    build:
      context: ./app2
    container_name: app2
    ports:
      - "8082:80" 

  app3:
    build:
      context: ./app3
    container_name: app3
    ports:
      - "8083:80"  
